complexData = { ...
    false 'IAP' 3 false 'AI' 3; ...
    false 'PR1' 3 false 'ML' 3 ; ...
    false 'PR2' 3 false 'EXP' 3  ; ...
    false 'ADS' 3 false 'NN'  3 ; ...
    false 'AAD' 3 false 'FZL' 3 ; ...
    false 'SAD' 3 false 'CN'  3 ; ...
    false 'SW1' 3 false 'OS1' 3  ; ...
    false 'SW2' 3 false 'OS2' 3 ; ...
    false 'SP'  3 false 'DB1'  3 ; ...
    false 'PLP' 3 false 'DB2' 3 ; ...
    false 'LC'  3 false 'ADB'  3 ; ...
    false 'CL'  1 false 'DSSM' 3 ; ...
    false 'NA' 3  false 'CS'  3 ; ...
    false 'CAL1' 3 false 'CnS' 3 ; ...
    false 'CAL2' 3 false 'IT'  3 ; ...
    false 'PS'  3 false 'PL'  3 ; ...
    false 'OR'  3 false 'NLP' 3 ; ...
    false 'DM'  3 false 'MM'  3 ; ...
    false 'CG'  3 false 'VR'  3 ; ...
    false 'Junior' 2 false 'Senior' 4};
